---
title: '2020-11-25'
author: '20201002'
date: "2020/11/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
str(example)
df_example<-data.frame(example)
```
```{r}
example$name[c(T, F, T, F)]
```

```{r}
str(example[c("name","height")])

pick_above170 <- example$height >= 170
example$height
c(175, 166, 170, 160) >= 170

example$name[pick_above170]
```
```{r}
example$birthday
class(example$birthday)
typeof(example$birthday)
```
```{r}
print(example[c("name","birthday")])

pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01")
example$name[pick_after98]
```
```{r}
example$allowance %in% c("1001-2000","2000+")
```

```{r}
print(example[c("name","allowance")])
levels(example)
```
```{r}
example$allowance<-
  order(example$allowance)
levels(example$allowance)
```

